MODE: 1                         # 1: train 2: test 3: eval
MODEL: 3                        # 1: edge model 2: inpaint model 3: edge-inpaint model 4: joint model
MASK: 3                         # 1: random block 2: half 3: external 4: (external random block) 5: (external random block half)
EDGE: 1                         # 1: canny 2: external
NMS: 1                          # 0: no non-max-suppression 1: applies non-max-suppression on the external edges by multiplying by Canny
SEED: 10                        # random seed
GPU:                            # list of gpu ids
  - 0                        
DEBUG: 1                        # turns on debugging mode
VERBOSE: 0                      # turns on verbose mode in the output console
DEVICE: cuda:0                  # device to be running the model on
NUM_WORKERS: 8                  # number of worker threads utilized in data loading.
PATH: <PATH TO OUTPUT DIR>
RESULTS: NULL

TRAIN_FLIST: <PATH TO TRAINING SET IMAGES>
TRAIN_EDGE_FLIST: <PATH TO TRAINING SET EDGES (can be nonexistant)>
TRAIN_MASK_FLIST: <PATH TO TRAINING SET MASKS>

VAL_FLIST: <PATH TO VAL SET IMAGES>
VAL_EDGE_FLIST: <PATH TO VAL SET EDGES (can be nonexistant)>
VAL_MASK_FLIST: <PATH TO VAL SET MASKS>

TEST_FLIST: <PATH TO TEST SET IMAGES>
TEST_EDGE_FLIST: <PATH TO TEST SET EDGES (can be nonexistant)>
VATEST_MASK_FLIST: <PATH TO TEST SET MASKS>
 
SOLVER:
  LR: 0.000001                      # learning rate
  D2G_LR: 0.1                     # discriminator/generator learning rate ratio
  BETA1: 0.0                      # adam optimizer beta1
  BETA2: 0.9                      # adam optimizer beta2
  BATCH_SIZE: 8                   # input batch size for training
  INPUT_SIZE: 256                 # input image size for training 0 for original size
  SIGMA: 2                        # standard deviation of the Gaussian filter used in Canny edge detector (0: random -1: no edge)
  MAX_ITERS: 2000000              # maximum number of iterations to train the model

LOSS:
  EDGE_THRESHOLD: 0.5             # edge detection threshold
  L1_LOSS_WEIGHT: 1               # l1 loss weight
  FM_LOSS_WEIGHT: 10              # feature-matching loss weight
  STYLE_LOSS_WEIGHT: 1            # style loss weight
  CONTENT_LOSS_WEIGHT: 1          # perceptual loss weight
  INPAINT_ADV_LOSS_WEIGHT: 0.01   # adversarial loss weight
  GAN_LOSS: nsgan                 # nsgan | lsgan | hinge
  GAN_POOL_SIZE: 0                # fake images pool size

LOGGING:
  SAVE_INTERVAL: 1000             # how many iterations to wait before saving model (0: never)
  EVAL_INTERVAL: 0                # how many iterations to wait before model evaluation (0: never)
  LOG_INTERVAL: 10                # how many iterations to wait before logging training status (0: never)